# Generated by Django 4.2 on 2023-05-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_todo', to='todo.group'),
        ),
    ]
